"""Per-product BCIR enabled flags aligned with 0519 common.db BCIR_STANDARD templates."""
from __future__ import annotations

BCIR_LEDGER_INPUT_ITEM_ENABLED = False

BCIR_ITEM_ENABLED_BY_PRODUCT: dict[str, dict[str, dict[str, bool]]] = {
    "A": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": True,
            "风险运营费用": True,
            "新开通客户投入": False,
            "专项费用": True,
            "其他客户运营": True,
            "内催费用": True,
            "其他风险运营": True
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "A01": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": True,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "客户运营费用": True,
            "风险运营费用": True,
            "新开通客户投入": True,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": True,
            "其他风险运营": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": True,
            "存客营销支出": True
        },
        "output": {
            "经营指标": True,
            "LUM规模": True,
            "客户数量": True,
            "日均LUM": True,
            "新客日均LUM": True,
            "存客日均LUM": True,
            "平均有效客户数": True,
            "新开通客户数": True,
            "营业收入": True,
            "内催回收额": True
        }
    },
    "A02": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "AuM规模": True,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "平均有效客户数": False,
            "新开通客户数": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "存客日均AuM": True,
            "新客AuM余额": True,
            "日均AuM": True
        }
    },
    "A03": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "新发放投入": True,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": False,
            "销售人力费用": False,
            "积分": False,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": True,
            "风险运营费用": True,
            "新开通客户投入": False,
            "专项费用": True,
            "其他客户运营": True,
            "内催费用": True,
            "其他风险运营": True
        },
        "output": {
            "经营指标": True,
            "LUM规模": True,
            "客户数量": True,
            "营业收入": True,
            "内催回收额": False,
            "平均有效客户数": True,
            "新开通客户数": False,
            "日均LUM": True,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "新发放LUM": True,
            "新发放LUM（标服）": True
        }
    },
    "A04": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": True,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": True,
            "存客营销支出": True,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "AuM规模": True,
            "客户数量": True,
            "营业收入": True,
            "内催回收额": False,
            "平均有效客户数": False,
            "新开通客户数": False,
            "MFAU客户数": True,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "存客日均AuM": True,
            "新客AuM余额": True,
            "日均AuM": True
        }
    },
    "A05": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "平均有效客户数": False,
            "新开通客户数": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False
        }
    },
    "B": {
        "input": {
            "业务支出合计": True,
            "营销支出（客户维度）": False,
            "新发放投入": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": True,
            "风险运营费用": True,
            "新开通客户投入": False,
            "专项运营": True,
            "其他客户运营": True,
            "内催费用": True,
            "其他风险运营": True
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入（还原）": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "新发放LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "B01": {
        "input": {
            "业务支出合计": True,
            "营销支出（客户维度）": True,
            "新发放投入": True,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": True,
            "存客营销支出": True,
            "客户运营费用": True,
            "风险运营费用": True,
            "新开通客户投入": False,
            "专项运营": False,
            "其他客户运营": False,
            "内催费用": True,
            "其他风险运营": True
        },
        "output": {
            "经营指标": True,
            "LUM规模": True,
            "客户数量": True,
            "营业收入（还原）": True,
            "内催回收额": True,
            "平均有效客户数": True,
            "新开通客户数": False,
            "日均LUM": True,
            "新客日均LUM": True,
            "存客日均LUM": True,
            "新发放LUM": True
        }
    },
    "B02": {
        "input": {
            "业务支出合计": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项运营": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入（还原）": True,
            "内催回收额": False,
            "平均有效客户数": False,
            "新开通客户数": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False
        }
    },
    "C": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "C01": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "C02": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": True,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "D": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "D01": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "E": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "E01": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "F": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    },
    "F01": {
        "input": {
            "业务支出": True,
            "营销支出（客户维度）": False,
            "营销支出": True,
            "运营费用（不含存款保险费）": True,
            "营销费用": True,
            "销售人力费用": True,
            "积分": True,
            "新客营销支出": False,
            "存客营销支出": False,
            "客户运营费用": False,
            "风险运营费用": False,
            "新开通客户投入": False,
            "专项费用": False,
            "其他客户运营": False,
            "内催费用": False,
            "其他风险运营": False
        },
        "output": {
            "经营指标": True,
            "LUM规模": False,
            "客户数量": False,
            "营业收入": True,
            "内催回收额": False,
            "日均LUM": False,
            "新客日均LUM": False,
            "存客日均LUM": False,
            "平均有效客户数": False,
            "新开通客户数": False
        }
    }
}

BCIR_INDICATOR_ENABLED_BY_PRODUCT: dict[str, dict[str, bool]] = {
    "A": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "A01": {
        "核心费率指标": True,
        "营销费率指标": True,
        "运营专项指标": True,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": True,
        "新客营销日均LUM费率": True,
        "新开通客户户均成本": True,
        "存客营销日均LUM费率": True,
        "运营费用日均LUM费率": True,
        "户均客户运营成本": True,
        "内催费率": True,
        "其他风险运营费率": True
    },
    "A02": {
        "核心费率指标": True,
        "营销费率指标": True,
        "运营专项指标": True,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均AuM费率": True,
        "新客营销AuM余额费率": False,
        "存客营销日均AuM费率": False,
        "新开通客户户均成本": False,
        "运营费用日均AuM费率": True,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "A03": {
        "核心费率指标": True,
        "营销费率指标": True,
        "运营专项指标": True,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": True,
        "新客营销日均LUM费率": False,
        "存客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "新发放LUM费率": True,
        "运营费用日均LUM费率": True,
        "户均客户运营成本": True,
        "标服3.0发放费率": True,
        "内催费率": True,
        "其他风险运营费率": True
    },
    "A04": {
        "核心费率指标": True,
        "营销费率指标": True,
        "运营专项指标": True,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均AuM费率": True,
        "新客营销AuM余额费率": True,
        "存客营销日均AuM费率": True,
        "新开通客户户均成本": False,
        "运营费用日均AuM费率": True,
        "MFAU户均客户运营成本": True,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "A05": {
        "核心费率指标": True,
        "营销费率指标": True,
        "运营专项指标": True,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": True,
        "新客营销日均LUM费率": False,
        "存客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "运营费用日均LUM费率": True,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "B": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "新发放LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "B01": {
        "核心费率指标": True,
        "营销费率指标": True,
        "运营专项指标": True,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": True,
        "新客营销日均LUM费率": True,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": True,
        "新发放LUM费率": True,
        "运营费用日均LUM费率": True,
        "户均客户运营成本": True,
        "内催费率": True,
        "其他风险运营费率": True
    },
    "B02": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "新客营销日均LUM费率": True,
        "存客营销日均LUM费率": True,
        "营销支出日均LUM费率": True,
        "新开通客户户均成本": True,
        "户均客户运营成本": True,
        "内催费率": True,
        "其他风险运营费率": True,
        "运营费用日均LUM费率": True
    },
    "C": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "C01": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "C02": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "D": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "D01": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "E": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "E01": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "F": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    },
    "F01": {
        "核心费率指标": True,
        "营销费率指标": False,
        "运营专项指标": False,
        "业务支出成本收入比": True,
        "营销支出收入费率": True,
        "运营费用收入费率": True,
        "营销支出日均LUM费率": False,
        "新客营销日均LUM费率": False,
        "新开通客户户均成本": False,
        "存客营销日均LUM费率": False,
        "运营费用日均LUM费率": False,
        "户均客户运营成本": False,
        "内催费率": False,
        "其他风险运营费率": False
    }
}

def bcir_item_enabled(product_code: str, section: str, name: str, *, default: bool = True) -> bool:
    if name in {"账套核对（运营不含存款保险）", "运营费用", "存款保险费（减项）"}:
        return BCIR_LEDGER_INPUT_ITEM_ENABLED
    product = str(product_code or "").strip().upper()
    section_key = str(section or "").strip().lower()
    item_name = str(name or "").strip()
    section_map = BCIR_ITEM_ENABLED_BY_PRODUCT.get(product, {}).get(section_key, {})
    if item_name in section_map:
        return section_map[item_name]
    return default


def bcir_indicator_enabled(product_code: str, name: str, *, default: bool = True) -> bool:
    product = str(product_code or "").strip().upper()
    indicator_name = str(name or "").strip()
    product_map = BCIR_INDICATOR_ENABLED_BY_PRODUCT.get(product, {})
    if indicator_name in product_map:
        return product_map[indicator_name]
    return default
